# Generated by Django 4.2.11 on 2026-09-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=3000)),
                ('handled', models.BooleanField(default=False)),
                ('whatsapp_alerted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('accent', models.CharField(choices=[('cyan', 'Cyan (Academic)'), ('green', 'Green (Career)'), ('purple', 'Purple (Business)'), ('orange', 'Orange (Technology)')], default='cyan', max_length=10)),
                ('blurb', models.CharField(blank=True, max_length=250)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('provider_response', models.TextField(blank=True)),
                ('related_ref', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'WhatsApp outbox entry',
                'verbose_name_plural': 'WhatsApp outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField()),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('open_ended', models.BooleanField(default=False)),
                ('unit', models.CharField(choices=[('', 'fixed price'), ('per_page', 'Per Page'), ('per_month', 'Per Month')], default='', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hello.servicecategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact_via_whatsapp', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brief', models.TextField(max_length=4000)),
                ('attachment', models.FileField(blank=True, max_length=255, upload_to='quote_briefs/%y/%m')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('whatsapp_alerted', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='hello.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
