"""
Django settings for myrailabs project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def env(key, default=None):
    """Read an environment variable, falling back to a local .env file if present."""
    val = os.environ.get(key)
    if val is not None:
        return val
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        try:
            for line in env_file.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                if k.strip() == key:
                    return v.strip().strip('"').strip("'")
        except OSError:
            pass
    return default


def env_bool(key, default="False"):
    return str(env(key, default)).strip().lower() in ("1", "true", "yes", "on")


def env_int(key, default=0):
    try:
        return int(str(env(key, default)))
    except (TypeError, ValueError):
        return default


# SECURITY
SECRET_KEY = env(
    "SECRET_KEY",
    "django-insecure-530&!d859$(w9wb-_kln9=spacz_(*f+=s@k&(4^sgini1%64a",
)
DEBUG = env_bool("DEBUG", "True")
ALLOWED_HOSTS = [
    h.strip()
    for h in env("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,.ngrok-free.app").split(",")
    if h.strip()
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in env(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:8001,http://127.0.0.1:8001,https://*.ngrok-free.app"
    ).split(",")
    if o.strip()
]

INSTALLED_APPS = [
    'hello',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myrailabs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hello.context.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'myrailabs.wsgi.application'


# Database
if env("DB_ENGINE", "").startswith("postgres"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME", "myrailabs"),
            "USER": env("DB_USER", "myrailabs"),
            "PASSWORD": env("DB_PASSWORD", ""),
            "HOST": env("DB_HOST", "127.0.0.1"),
            "PORT": env("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization — Myrai Labs operates on SA time
LANGUAGE_CODE = "en-za"
TIME_ZONE = env("TIME_ZONE", "Africa/Johannesburg")
USE_I18N = True
USE_TZ = True

# Static & media
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "hello" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = Path(env("MEDIA_ROOT", str(BASE_DIR / "media")))

DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Myrai Labs business identity
BUSINESS_NAME = "Myrai Labs"
BUSINESS_TAGLINE = "Digital Solutions. Intelligent Systems. Verified Impact."
BUSINESS_PHONE = env("BUSINESS_PHONE", "078 233 9131")
BUSINESS_EMAIL = env("BUSINESS_EMAIL", "info@myrailabs.com")
BUSINESS_LOCATION = "Giyani, Limpopo, South Africa, 0826"

def _to_wa_intl(number):
    """Normalise an SA number (078 233 9131) to international (27782339131)."""
    digits = "".join(c for c in number if c.isdigit())
    if digits.startswith("0"):
        return "27" + digits[1:]
    return digits

WHATSAPP_NUMBER = _to_wa_intl(BUSINESS_PHONE)

# Email
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", "")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", "True")
EMAIL_HOST_USER = env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", "vuentib@gmail.com")
ADMIN_NOTIFY_EMAIL = env("ADMIN_NOTIFY_EMAIL", BUSINESS_EMAIL)

# WhatsApp
WHATSAPP_ENABLED = env_bool("WHATSAPP_ENABLED", "False")
WHATSAPP_PHONE_ID = env("WHATSAPP_PHONE_ID", "")
WHATSAPP_TOKEN = env("WHATSAPP_TOKEN", "")
WHATSAPP_API_VERSION = env("WHATSAPP_API_VERSION", "v21.0")
WHATSAPP_ALERT_TO = env("WHATSAPP_ALERT_TO", WHATSAPP_NUMBER)

# Anti-spam throttles
QUOTE_MAX_PER_HOUR = env_int("QUOTE_MAX_PER_HOUR", 5)
CONTACT_MAX_PER_HOUR = env_int("CONTACT_MAX_PER_HOUR", 10)

# Admin branding
ADMINS = [("Myrai Labs", ADMIN_NOTIFY_EMAIL)] if ADMIN_NOTIFY_EMAIL else []